[package]
name = "parallel"
version = "0.1.0"
authors = ["parsa <mr.parsoli@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.4.0"
